name: Release OSX

on:
  release:
    types: [published]

jobs:
  build-intel:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
      - name: Generate OSX Intel Package
        run: mvn --batch-mode package -Drelease=osx-intel

      - name: Upload Jar Artifact
        uses: JasonEtco/upload-to-release@master
        with:
          args: target/mdiag-release-osx-intel-${{ github.event.release.tag_name }}.jar application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate md5 checksum
        run: md5sum < target/mdiag-release-osx-intel-${{ github.event.release.tag_name }}.jar | awk '{print $1}' > target/mdiag-release-osx-intel-${{ github.event.release.tag_name }}.jar.md5

      - name: Upload md5 checksum
        uses: JasonEtco/upload-to-release@master
        with:
          args: target/mdiag-release-osx-intel-${{ github.event.release.tag_name }}.jar.md5 text/plain
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-arm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
      - name: Generate OSX ARM Package
        run: mvn --batch-mode package -Drelease=osx-aarch64

      - name: Upload Jar Artifact
        uses: JasonEtco/upload-to-release@master
        with:
          args: target/mdiag-release-osx-aarch64-${{ github.event.release.tag_name }}.jar application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate md5 checksum
        run: md5sum < target/mdiag-release-osx-aarch64-${{ github.event.release.tag_name }}.jar | awk '{print $1}' > target/mdiag-release-osx-aarch64-${{ github.event.release.tag_name }}.jar.md5

      - name: Upload md5 checksum
        uses: JasonEtco/upload-to-release@master
        with:
          args: target/mdiag-release-osx-aarch64-${{ github.event.release.tag_name }}.jar.md5 text/plain
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}